os: osx
osx_image: xcode11.3.1
language: swift
script: xcodebuild clean build test -project /Users/lucagramaglia/Documents/Programming/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

